### ISSUE TITLE
Explicitly set ip for d.pboehm.de domain

### ISSUE THREAD

**Issue by LennyPenny** [pboehm/ddns#10]
Hey, 
I think my ISP is doing something that makes your `/update` thingy see a falsified IP  (http://myip.is and similar see a different one too)

How do you feel about adding an `/update/{domain}/{token}/{ip}` route to explicitly set IPs?

**Comment by pboehm** [comment]
Hello,

for me this sounds like your ISP runs a Dual Stack Lite setup where you're only getting an IPv6 Address(-Prefix) and IPv4-Traffic is handled via Carrier-grade NAT through specific hardware located at your ISP. This is the case for example in Germany within the cable network of Vodafone/Kabeldeutschland.

With this setup your requests to ddns.pboehm.de could have different IPv4-Source-Addresses on each request and also different addresses each time you're accessing http://myip.is. The big problem with this setup is, that you can't access your own router via the public IPv4 address because you're only reaching the Carrier-grade NAT router of your ISP.

The real solution would be that ddns.pboehm.de would be reachable via IPv6 so that your requests to ddns.pboehm.de would be made via IPv6 and the IPv6-Address would be registered and returned when resolving your domain. Currently ddns.pboehm.de is missing the required AAAA records and is hasn't been tested with IPv6. If we are registering IPv6-Addresses you can only reach you host from networks where IPv6 is supported, which could be a problem.

Adding the suggested route would probably not fix your problem and I could see some possible security problems when the IP address is passed by the user.

**Comment by dumblob** [comment]
Just reading through issues with this piece of software and I'm curious whether the testing instance `d.pboehm.de` will get support for IPv6 soon. Or do you happen to know about other instances of this cute piece of software which do support both IPv4 and IPv6 simultaneously (i.e. once the user will `curl ...` through IPv6 and once through IPv4).
