### ISSUE TITLE
Caddy cannot start because of lets encrypt

### ISSUE THREAD

**Issue by Rinma** [pboehm/ddns#11]
When i start the server and look into the log
```
caddy_1     | Your sites will be served over HTTPS automatically using Let's Encrypt.
caddy_1     | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
caddy_1     |   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
caddy_1     | 2018/05/12 15:24:11 user must agree to CA terms (use -agree flag)
caddy_1     | exit status 1
caddy_1     | Do you agree to the terms? (y/n): y
docker_caddy_1 exited with code 1
```

How can i fix this?

**Comment by pboehm** [comment]
Hi Rinma,

sorry for my late reply but I was on a short vacation. Your problem seems to be a change introduced in one of the latest Caddy versions. It now requires explicitly accepting the CA terms by providing the `-agree` flag. The Caddy docker image used in the setup provides an environment variable `ACME_AGREE=true` for accepting the terms https://github.com/abiosoft/caddy-docker#lets-encrypt-subscriber-agreement.

Please make sure that you have the latest version of the abiosoft/caddy docker image installed and add the following snippet after the following line https://github.com/pboehm/ddns/blob/master/docker/docker-compose.override.yml.sample#L25 :

```
ACME_AGREE: true
```

**Comment by fusion44** [comment]
You have to put true in quotes, otherwise, you'll get another error:
ACME_AGREE: "true"

**Comment by pboehm** [comment]
I've updated the `docker-compose.override.yml.sample` in 13dae077d905526ba6db274025db779a1831edc7 and it now contains the `ACME_AGREE` env variable.
