### ISSUE TITLE
possibility to disable autocertbot?

### ISSUE THREAD

**Issue by agustt** [pboehm/ddns#25]
is there any way to disable certbot at startup? for situations where you already have the certificate, you don't need the creation and it's stopping the server to boot up.

**Comment by pboehm** [comment]
Hello,

there is no certbot included in the suggested deployment of `ddns` but there is the webserver Caddy 1 (not Version 2 which is the default now) that has an automatic/automagic HTTPS feature which is enabled by default. You have multiple options here:

* use another webserver container instead of caddy
* disable HTTPS by replacing the first line in `docker/caddy/Caddyfile` with `http://{$DDNS_CADDY_DOMAIN} {`
* configure Caddy (old docs as tar.gz https://caddyserver.com/caddy-v1-docs-archive.tar.gz) to use preexisting certificates and mount these certificates into the `caddy` container

**Comment by agustt** [comment]
> Hello,
> 
> there is no certbot included in the suggested deployment of `ddns` but there is the webserver Caddy 1 (not Version 2 which is the default now) that has an automatic/automagic HTTPS feature which is enabled by default. You have multiple options here:
> 
> * use another webserver container instead of caddy
> * disable HTTPS by replacing the first line in `docker/caddy/Caddyfile` with `http://{$DDNS_CADDY_DOMAIN} {`
> * configure Caddy (old docs as tar.gz https://caddyserver.com/caddy-v1-docs-archive.tar.gz) to use preexisting certificates and mount these certificates into the `caddy` container

That did the thing. 

Thank you very much!
