### ISSUE TITLE
certificate has expired after Aug 10 06:13:43 2021 GMT

### ISSUE THREAD

**Issue by yougg** [pboehm/ddns#39]
> $`curl https://ddns.pboehm.de/`
> curl: (60) SSL certificate problem: certificate has expired

> $`echo | openssl s_client -showcerts -servername ddns.pboehm.de -connect ddns.pboehm.de:443 2>/dev/null | openssl x509 -inform pem -noout -text`

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:ff:ef:3d:78:9a:8a:2c:aa:36:11:8b:26:49:c4:64:0f:25
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Let's Encrypt, CN=R3
        Validity
            Not Before: May 12 06:13:43 2021 GMT
            Not After : Aug 10 06:13:43 2021 GMT
        Subject: CN=ddns.pboehm.de
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:cd:da:89:12:c2:f4:3b:f9:13:a0:aa:dc:57:b4:
                    8f:65:c0:b6:9b:f7:0a:c9:00:b0:e1:ad:64:22:33:
                    0b:01:fb:53:34:4b:ef:a5:fb:79:dc:7a:c9:32:8e:
                    51:6a:d9:cd:35:c2:8e:5f:c2:7e:6f:1f:43:6b:41:
......
......
```

**Comment by pboehm** [comment]
Hi @yougg,

thanks for reporting this problem!

The setup of ddns.pboehm.de is a bit different than the proposed `ddns` setup and there was an older version of `caddy` running that had no support for ACME v2. Lets Encrypt does not allow certificate renewal via ACME v1 anymore, so that the certificates have expired without a notice. I fixed it by upgrading caddy but ran into a Lets Encrypt rate limit 😞 which resulted in some downtime.

It should work again.
