### ISSUE TITLE
pdns failing to launch, permission denied

### ISSUE THREAD

**Issue by Intel1146** [pboehm/ddns#7]
```
pdns_server[21066]: Creating backend connection for TCP
pdns_server[21066]: [PIPEBackend] Unable to launch, fatal argument error: Command '/home/moist/gocode/bin/ddns' cannot be executed: Permission denied
pdns_server[21066]: Caught an exception instantiating a backend: Command '/home/moist/gocode/bin/ddns' cannot be executed: Permission denied
pdns_server[21066]: Cleaning up
pdns_server[21066]: TCP server is unable to launch backends - will try again when questions come in: Command '/home/moist/gocode/bin/ddns' cannot be executed: Permission denied
systemd[1]: Started PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit pdns.service has finished starting up.
--
-- The start-up result is done.
pdns_server[21066]: About to create 3 backend threads for UDP
pdns_server[21066]: [PIPEBackend] Unable to launch, fatal argument error: Command '/home/moist/gocode/bin/ddns' cannot be executed: Permission denied
pdns_server[21066]: Caught an exception instantiating a backend: Command '/home/moist/gocode/bin/ddns' cannot be executed: Permission denied
pdns_server[21066]: Cleaning up
pdns_server[21066]: Distributor caught fatal exception: Command '/home/moist/gocode/bin/ddns' cannot be executed: Permission denied
systemd[1]: pdns.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: pdns.service: Unit entered failed state.
systemd[1]: pdns.service: Failed with result 'exit-code'.
```
Running Ubuntu 16.04 LTS
I have given `/bin/ddns` executable permissions, but every time I restart `pdns` it fails. I think I might have the wrong version of `pdns`. 

What version of pdns did you use for this project?

I thought my domain records were configured incorrectly, which is why I asked you how you set them up. This is actually the problem I was having the whole time.

**Comment by pboehm** [comment]
Hello,

for me this looks like a permission problem, that pdns_server is executed as a separate user by systemd, which has no access to the complete path /home/moist/gocode/bin/. I would recommend moving the ddns binary to /usr/local/bin with 755 as permissions and adjusting all paths to that location. Systemd also provides some features where it isolates the home directory from its services, which could also be a problem here.

When https://github.com/pboehm/ddns/pull/2 is merged, we don't have this problem anymore because it provides a docker setup but also uses the PowerDNS Remote Backend with HTTP calls, where only the frontend part of ddns has to executed, and PowerDNS makes some calls to the frontend.

Philipp

**Comment by Intel1146** [comment]
I replaced the source and binary with the `docker_and_rework' branch. I am getting errors about a child process closing a pipe. I am going to make a clean Debian server and start from scratch from the `docker_and_rework` branch. I assume the setup process will be a little but different when using this branch.

**Comment by pboehm** [comment]
I wouldn't recommend the `docker_and_rework` branch for now, because it is work in progress and the corresponding `docker-compose.override.yaml` isn't documented for now. It should be in a usable state, around next week.

Sorry for the inconvenience.

**Comment by BonusHunt** [comment]
Intel, next time you leave me a message you should take the time to read what was said because I was not being an asshole I was explaining why a lot of people are having issues and that is because of his documentation.. Given the fact you're only jumping on pboehm's dick is because you want his help when from a users point of view is a complete asshole with this "only those good enough to sift through my cryptic installation instructions can use my source, those who maybe trying to learn a thing or two can fuck off".

Firstly which according to your log I believe you have already done this, if you have not go ahead and head to `/etc/powerdns` you should have a file and a folder ([screenshot](https://i.gyazo.com/da833dce5f1d0324063e5d31848c6dc2.png)), if you have anything else rm that shit instantly. Head into the `pdns.d` folder, there should be like... some .local files if I am mistaken, also rm that shit get it out of there that was causing some error `Fatal error: Trying to set unknown parameter 'bind-config'`. That folder should contain your `pipe.conf` file only. Now we are good, head to your folder here `/home/moist/gocode/bin/ddns` then type `sudo mv ddns /usr/local/bin`, for testing purpose do `chmod 777 /usr/local/bin/ddns`. Now you need to update `/etc/supervisor/conf.d/ddns.conf` and `/etc/powerdns/pdns.d/pipe.conf` with this path `/usr/local/bin/ddns` and your DNS records should look like this ([screenshot](https://i.gyazo.com/b77927d604034f76bbe3e74de562d9ad.png)) you can head to ddns.stealthy.pro to see this working although its going to be changing a lot.

Thanks phillip for this elegant piece of source but fuck you for putting me through 48 hours of bullshit. Oh and Intel, check your syslog file for any further errors and put them here ill help you as I understand how fucking irritating it is.

**Comment by BonusHunt** [comment]
Also do not forget - `sudo service pdns restart && sudo service supervisor restart && sudo service nginx restart`

**Comment by Intel1146** [comment]
**Pboehm**, thank you. It is really no inconvenience at all to wait a little bit for this branch to be updated. I can work on customizing the UI in the mean time. Sorry for the off topic comments, but this guy is pissing me off.

**BonusHunt**. I was not "jumping on pboehm's dick," I read your issue to see if there was anything in the thread that could help me. In fact, I removed my comment because I felt that it wasn't my job to defend him. The issue I have with you is that pboehm isn't under _any_ obligation to maintain or update this code, or provide it AT ALL. You threw a little fit because you didn't feel that his instructions were good enough, and he replied in a civil manner. 

Secondly, don't fucking speak for me. I don't want pboehm to spoon feed me, so don't say `10 minutes of your time could of saved days of myself and Intel's time.`, because it isn't true. I actually researched my problems, and I already did all the steps you provided. And no, it is not "fucking irritating" for me, since I don't feel entitled to be handed answers on a silver platter.

I don't need your help, I need you to kindly kiss a dick and fuck off.

**Comment by BonusHunt** [comment]
Let me just explain something to you dipshit, go here (https://github.com/pboehm/ddns/) and read, do you see that large bold title which states "Self-Hosted", something which CLEARLY implies the creator wants people to use his source on their own setups. Right, so we have established that fact lets move onto what I actually said because you have a very, very hard time reading. Why provide installation instructions for people to use the source if its fucking shite, meaning nobody can make ends meat and has no end of issues trying to decrypt installation instructions. Nobody is expecting to be provided answers on a silver platter, its bad etiquette to provide source, openly announce it as free to use but provide missing instructions then say 

> if you cant manage this service 'or decrypt my retarded installation instructions' you are not entitled to use it.

Meaning, 

> You're a fucking idiot, I cant be arsed to help you, figure out how to decrypt my installation instructions or dont use it.

You better hope you are squeaky clean Intel because ill be dropping your dox in this section within the next 24 hours for your inability to read.

**Comment by Intel1146** [comment]
No, motherfucker. I'm dirty as hell. You can do whatever you want, I honestly couldn't care less. I don't own ANY .ml or .tk domains, as I despise freenom. You can "drop my dox" all you fucking want to, you have my permission. ;) 

You seem to be completely unaware of how DNS works. A dns server isn't really a file server, see? It simply is a record of what hostnames should resolve to what IP addresses. So a dns server can't really "serve malware," which you would know if you has a basic understanding of what you are blathering on about. :)

**Comment by BonusHunt** [comment]
You're a funny kid honestly, secondly I am not even going to get into this with you, go and read (https://umbrella.cisco.com/blog/2013/04/15/on-the-trail-of-malicious-dynamic-dns-domains/), again you do have a very big problem with reading.

I will indeed drop your dox, following that and how you react there will be further repercussions. A lot of people can act like the internet gangster but every once in a while you will run into somebody who you should of not run your mouth off too. Today, unfortunately for you I am that person however we will see the outcome. I'll send you an email on that domain you currently own which is under WhoisGuard protection. I cant wait till that stomach of yours drops, oh boy.. You have a lot to learn.

**Comment by Intel1146** [comment]
Okay, kid. Have fun!

**Comment by BonusHunt** [comment]
I will do, be sure to google the username I will be emailing to you. You might think twice about running your mouth in future.

**Comment by Intel1146** [comment]
Hurry it up, man. I don't have all fucking day.

**Comment by pboehm** [comment]
@Intel1146 I only wanted to let you know that the rework of `ddns` including a docker setup has now been merged to master and the whole process of Self-Hosting should now be far more easy. The README contains the updated documentation.

**Comment by zenny** [comment]
@pboehm Thanks for updating ddns to install inside docker. Yet I prefer to go with lxc containers/KVM instances/FreeBSD jails (with the order of priority).
